/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description JWT bersifat stateless — server tidak menyimpan sesi apa pun.
         *
         *     Endpoint ini hanya penanda agar frontend punya tempat memanggil saat user
         *     menekan logout; token benar-benar dibuang di sisi klien. Kalau nanti butuh
         *     pencabutan token sungguhan, perlu denylist token di Redis/DB.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Ganti password sendiri — tersedia untuk semua role.
         *
         *     Password lama tetap diminta walaupun pemanggil sudah membawa token valid:
         *     tanpa itu, token yang dicuri bisa dipakai mengunci pemilik akun yang sah.
         */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Sales */
        post: operations["sync_sales_api_sync_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales */
        get: operations["get_sales_api_sales__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/colorplate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales Colorplate */
        get: operations["get_sales_colorplate_api_sales_colorplate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Kartu ringkasan di atas dashboard. Transaksi terhapus tidak dihitung.
         */
        get: operations["get_summary_api_sales_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily
         * @description Time series harian untuk grafik.
         */
        get: operations["get_daily_api_sales_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/by-outlet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get By Outlet
         * @description Perbandingan antar outlet — bukan hak user yang terikat satu outlet.
         */
        get: operations["get_by_outlet_api_sales_by_outlet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/top-products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Products */
        get: operations["get_top_products_api_sales_top_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Sales
         * @description Unduh transaksi sebagai CSV.
         *
         *     Tidak memakai pagination — ini memang dimaksudkan untuk menarik seluruh
         *     hasil filter. Batasi dengan rentang tanggal untuk data yang besar.
         */
        get: operations["export_sales_api_sales_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sale Detail
         * @description Detail satu transaksi beserta itemnya.
         *
         *     Transaksi milik outlet lain menghasilkan 404, bukan 403 — supaya nomor
         *     transaksi outlet lain tidak bisa dipetakan lewat beda status code.
         */
        get: operations["get_sale_detail_api_sales__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Sales
         * @description Dipicu mesin POS, bukan dashboard — karena itu tetap pakai API key outlet.
         */
        post: operations["publish_sales_api_sales_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outlets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Outlets
         * @description Daftar outlet untuk dropdown filter.
         *
         *     Sumbernya tabel `api_keys`: satu outlet = satu key. Hanya role yang berhak
         *     melihat lintas outlet yang boleh memanggilnya.
         */
        get: operations["list_outlets_api_outlets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outlets/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description Kapan tiap outlet terakhir mengirim data — untuk mendeteksi outlet yang mati.
         *
         *     Ditempatkan di sini, bukan di `/api/sync/status` seperti rencana awal:
         *     prefix `/api/sync` khusus autentikasi API key mesin POS, sedangkan ini
         *     dibaca manusia lewat dashboard.
         *
         *     Terbuka untuk semua role, tapi tetap ter-scope — user outlet hanya melihat
         *     outletnya sendiri.
         */
        get: operations["sync_status_api_outlets_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_api_api_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description Buat key untuk outlet baru.
         *
         *     Outlet yang sudah punya key ditolak, bukan ditimpa — menimpa berarti mesin
         *     POS di lapangan langsung kehilangan akses tanpa peringatan. Untuk mengganti
         *     key yang bocor, pakai endpoint rotate.
         */
        post: operations["create_api_key_api_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys/{outlet_code}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate Api Key
         * @description Ganti key outlet. Key lama langsung tidak berlaku.
         */
        post: operations["rotate_api_key_api_api_keys__outlet_code__rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys/{outlet_code}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Api Key
         * @description Nonaktifkan key. Barisnya tidak dihapus, demi jejak audit.
         */
        post: operations["revoke_api_key_api_api_keys__outlet_code__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset password user lain. Tidak butuh password lama — ini jalur admin.
         */
        post: operations["reset_password_api_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Endpoint publik — dipakai monitoring, tidak boleh butuh API key.
         */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Alias
         * @description Liveness probe — sengaja tidak menyentuh database.
         *
         *     Kalau probe ini ikut gagal saat database sedang bermasalah, orchestrator
         *     akan me-restart container yang sebenarnya sehat.
         */
        get: operations["health_alias_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness probe — memeriksa database sungguhan.
         *
         *     Mengembalikan 503 supaya load balancer mengeluarkan instance ini dari
         *     rotasi selama koneksi database bermasalah.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenResponse */
        AccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * ApiKeyCreatedResponse
         * @description Satu-satunya response yang memuat key mentah.
         */
        ApiKeyCreatedResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["ApiKeyResponse"];
            /** Api Key */
            api_key: string;
            /**
             * Message
             * @default Simpan key ini sekarang — tidak bisa dilihat lagi.
             */
            message: string;
        };
        /** ApiKeyDetailResponse */
        ApiKeyDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["ApiKeyResponse"];
        };
        /** ApiKeyListResponse */
        ApiKeyListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["ApiKeyResponse"][];
        };
        /**
         * ApiKeyResponse
         * @description Bentuk API key yang aman dikirim — tanpa key mentah maupun hash-nya.
         */
        ApiKeyResponse: {
            /** Outlet Code */
            outlet_code: string;
            /** Key Prefix */
            key_prefix?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ColorplateListResponse */
        ColorplateListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["ColorplateRow"][];
        };
        /** ColorplateRow */
        ColorplateRow: {
            /** Product Name */
            product_name?: string | null;
            /** Outlet Code */
            outlet_code?: string | null;
            /** Sale Date */
            sale_date?: string | null;
            /** Sold */
            sold: number;
        };
        /** CreateApiKeyRequest */
        CreateApiKeyRequest: {
            /** Outlet Code */
            outlet_code: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "manager" | "outlet";
            /** Outlet Code */
            outlet_code?: string | null;
            /** Full Name */
            full_name?: string | null;
        };
        /** DailyListResponse */
        DailyListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["DailyRow"][];
        };
        /** DailyRow */
        DailyRow: {
            /** Sale Date */
            sale_date?: string | null;
            /** Total Transactions */
            total_transactions: number;
            /** Total Amount */
            total_amount: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OutletListResponse */
        OutletListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["OutletResponse"][];
        };
        /** OutletResponse */
        OutletResponse: {
            /** Outlet Code */
            outlet_code: string;
            /** Is Active */
            is_active: boolean;
        };
        /** OutletSalesListResponse */
        OutletSalesListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["OutletSalesRow"][];
        };
        /** OutletSalesRow */
        OutletSalesRow: {
            /** Outlet Code */
            outlet_code?: string | null;
            /** Total Transactions */
            total_transactions: number;
            /** Total Amount */
            total_amount: number;
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /** PublishResponse */
        PublishResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Message */
            message: string;
            /** Outlet */
            outlet?: string | null;
            /** Date */
            date?: string | null;
            /**
             * Published
             * @default 0
             */
            published: number;
        };
        /** PublishSalesRequest */
        PublishSalesRequest: {
            /**
             * Exchange
             * @default posdata_exchange
             */
            exchange: string;
            /**
             * Routing Key
             * @default posdata.created
             */
            routing_key: string;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SaleDetail */
        SaleDetail: {
            /** Transaction Id */
            transaction_id: number;
            /** Outlet Code */
            outlet_code?: string | null;
            /** Shop Id */
            shop_id: number;
            /** Receipt Id */
            receipt_id: number;
            /** Reference No */
            reference_no?: string | null;
            /** Sale Date */
            sale_date?: string | null;
            /** Paid Time */
            paid_time?: string | null;
            /** Receipt Total Amount */
            receipt_total_amount: number;
            /** Receipt Pay Price */
            receipt_pay_price: number;
            /** Receipt Discount */
            receipt_discount: number;
            /** Transaction Status Id */
            transaction_status_id: number;
            /** Void Staff Id */
            void_staff_id: number;
            /**
             * Deleted
             * @default 0
             */
            deleted: number;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["SaleItemResponse"][];
        };
        /** SaleDetailResponse */
        SaleDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["SaleDetail"];
        };
        /** SaleItemResponse */
        SaleItemResponse: {
            /** Order Detail Id */
            order_detail_id: number;
            /** Transaction Id */
            transaction_id: number;
            /** Product Id */
            product_id: number;
            /** Product Group */
            product_group?: string | null;
            /** Product Dept */
            product_dept?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /** Retail Price */
            retail_price: number;
            /** Order Status Id */
            order_status_id: number;
            /** Void Staff Id */
            void_staff_id: number;
            /** Comment */
            comment?: string | null;
        };
        /** SaleResponse */
        SaleResponse: {
            /** Transaction Id */
            transaction_id: number;
            /** Outlet Code */
            outlet_code?: string | null;
            /** Shop Id */
            shop_id: number;
            /** Receipt Id */
            receipt_id: number;
            /** Reference No */
            reference_no?: string | null;
            /** Sale Date */
            sale_date?: string | null;
            /** Paid Time */
            paid_time?: string | null;
            /** Receipt Total Amount */
            receipt_total_amount: number;
            /** Receipt Pay Price */
            receipt_pay_price: number;
            /** Receipt Discount */
            receipt_discount: number;
            /** Transaction Status Id */
            transaction_status_id: number;
            /** Void Staff Id */
            void_staff_id: number;
            /**
             * Deleted
             * @default 0
             */
            deleted: number;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SalesItemSchema */
        SalesItemSchema: {
            /** Order Detail Id */
            order_detail_id: number;
            /** Transaction Id */
            transaction_id: number;
            /**
             * Sale Date
             * Format: date
             */
            sale_date: string;
            /** Product Id */
            product_id: number;
            /** Product Group */
            product_group?: string | null;
            /** Product Dept */
            product_dept?: string | null;
            /** Product Name */
            product_name?: string | null;
            /**
             * Product Set Type
             * @default 0
             */
            product_set_type: number;
            /**
             * Order Status Id
             * @default 2
             */
            order_status_id: number;
            /**
             * Sale Mode
             * @default 1
             */
            sale_mode: number;
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /**
             * Retail Price
             * @default 0
             */
            retail_price: number;
            /**
             * Minimum Price
             * @default 0
             */
            minimum_price: number;
            /** Comment */
            comment?: string | null;
            /**
             * Order Staff Id
             * @default 0
             */
            order_staff_id: number;
            /**
             * Order Table Id
             * @default 0
             */
            order_table_id: number;
            /**
             * Void Staff Id
             * @default 0
             */
            void_staff_id: number;
        };
        /** SalesListResponse */
        SalesListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["SaleResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** SalesSchema */
        SalesSchema: {
            /** Transaction Id */
            transaction_id: number;
            /**
             * Shop Id
             * @default 0
             */
            shop_id: number;
            /**
             * Receipt Year
             * @default 0
             */
            receipt_year: number;
            /**
             * Receipt Month
             * @default 0
             */
            receipt_month: number;
            /**
             * Receipt Id
             * @default 0
             */
            receipt_id: number;
            /** Reference No */
            reference_no?: string | null;
            /** Queue Name */
            queue_name?: string | null;
            /** Sale Date */
            sale_date?: string | null;
            /** Paid Time */
            paid_time?: string | null;
            /** Close Time */
            close_time?: string | null;
            /**
             * Open Staff Id
             * @default 0
             */
            open_staff_id: number;
            /**
             * Paid Staff Id
             * @default 0
             */
            paid_staff_id: number;
            /**
             * Comm Staff Id
             * @default 0
             */
            comm_staff_id: number;
            /**
             * Void Staff Id
             * @default 0
             */
            void_staff_id: number;
            /** Void Reason */
            void_reason?: string | null;
            /** Void Time */
            void_time?: string | null;
            /**
             * Transaction Status Id
             * @default 1
             */
            transaction_status_id: number;
            /**
             * Sale Mode
             * @default 1
             */
            sale_mode: number;
            /**
             * Deleted
             * @default 0
             */
            deleted: number;
            /**
             * No Customer
             * @default 1
             */
            no_customer: number;
            /**
             * Other Percent Discount
             * @default 0
             */
            other_percent_discount: number;
            /**
             * Other Amount Discount
             * @default 0
             */
            other_amount_discount: number;
            /**
             * Receipt Product Retail Price
             * @default 0
             */
            receipt_product_retail_price: number;
            /**
             * Receipt Sale Price
             * @default 0
             */
            receipt_sale_price: number;
            /**
             * Receipt Pay Price
             * @default 0
             */
            receipt_pay_price: number;
            /**
             * Receipt Discount
             * @default 0
             */
            receipt_discount: number;
            /**
             * Receipt Total Amount
             * @default 0
             */
            receipt_total_amount: number;
            /**
             * Vat Percent
             * @default 0
             */
            vat_percent: number;
            /**
             * Transaction Vat
             * @default 0
             */
            transaction_vat: number;
            /**
             * Transaction Exclude Vat
             * @default 0
             */
            transaction_exclude_vat: number;
            /**
             * Transaction Vatable
             * @default 0
             */
            transaction_vatable: number;
            /**
             * Service Charge Percent
             * @default 0
             */
            service_charge_percent: number;
            /**
             * Service Charge
             * @default 0
             */
            service_charge: number;
            /**
             * Service Charge Vat
             * @default 0
             */
            service_charge_vat: number;
            /**
             * Other Income
             * @default 0
             */
            other_income: number;
            /**
             * Other Income Vat
             * @default 0
             */
            other_income_vat: number;
            /** Transaction Note */
            transaction_note?: string | null;
            /**
             * Is Split Transaction
             * @default 0
             */
            is_split_transaction: number;
            /**
             * Is From Other Transaction
             * @default 0
             */
            is_from_other_transaction: number;
            /** Items */
            items?: components["schemas"]["SalesItemSchema"][];
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Password */
            password: string;
        };
        /** SimpleResponse */
        SimpleResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** SummaryData */
        SummaryData: {
            /** Total Transactions */
            total_transactions: number;
            /** Total Amount */
            total_amount: number;
            /** Total Discount */
            total_discount: number;
            /** Average Per Transaction */
            average_per_transaction: number;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["SummaryData"];
        };
        /** SyncRequestSchema */
        SyncRequestSchema: {
            /**
             * Sales
             * @description Maksimal 1000 transaksi per request
             */
            sales: components["schemas"]["SalesSchema"][];
        };
        /** SyncResponse */
        SyncResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Inserted Sales */
            inserted_sales: number;
            /** Inserted Items */
            inserted_items: number;
        };
        /** SyncStatusListResponse */
        SyncStatusListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["SyncStatusRow"][];
        };
        /** SyncStatusRow */
        SyncStatusRow: {
            /** Outlet Code */
            outlet_code?: string | null;
            /** Last Sale Date */
            last_sale_date?: string | null;
            /** Last Synced At */
            last_synced_at?: string | null;
            /** Total Transactions */
            total_transactions: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserResponse"];
        };
        /** TopProductListResponse */
        TopProductListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["TopProductRow"][];
        };
        /** TopProductRow */
        TopProductRow: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name?: string | null;
            /** Product Group */
            product_group?: string | null;
            /** Total Qty */
            total_qty: number;
            /** Total Amount */
            total_amount: number;
        };
        /**
         * UpdateUserRequest
         * @description Semua field opsional — hanya yang dikirim yang diubah.
         *
         *     `email` sengaja tidak ada: email adalah subject JWT, mengubahnya membuat
         *     token yang sedang berjalan menunjuk user yang tidak ada lagi.
         */
        UpdateUserRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role?: ("admin" | "manager" | "outlet") | null;
            /** Outlet Code */
            outlet_code?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UserAdminResponse */
        UserAdminResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role: string;
            /** Outlet Code */
            outlet_code?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** UserDetailResponse */
        UserDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["UserAdminResponse"];
        };
        /** UserListResponse */
        UserListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["UserAdminResponse"][];
        };
        /**
         * UserResponse
         * @description Bentuk user yang boleh dikirim ke frontend — tanpa password_hash.
         */
        UserResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role: string;
            /** Outlet Code */
            outlet_code?: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_sales_api_sync_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_api_sales__get: {
        parameters: {
            query?: {
                /** @description Kode outlet; diabaikan untuk role 'outlet' */
                outlet?: string | null;
                /** @description Tanggal awal (inklusif) */
                start_date?: string | null;
                /** @description Tanggal akhir (inklusif) */
                end_date?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_colorplate_api_sales_colorplate_get: {
        parameters: {
            query?: {
                /** @description Kode outlet; diabaikan untuk role 'outlet' */
                outlet?: string | null;
                /** @description Tanggal awal (inklusif) */
                start_date?: string | null;
                /** @description Tanggal akhir (inklusif) */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorplateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_sales_summary_get: {
        parameters: {
            query?: {
                outlet?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_api_sales_daily_get: {
        parameters: {
            query?: {
                outlet?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_outlet_api_sales_by_outlet_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutletSalesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_products_api_sales_top_products_get: {
        parameters: {
            query?: {
                outlet?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                product_group?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_sales_api_sales_export_get: {
        parameters: {
            query?: {
                outlet?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sale_detail_api_sales__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Nomor transaksi dari POS */
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_sales_api_sales_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishSalesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outlets_api_outlets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutletListResponse"];
                };
            };
        };
    };
    sync_status_api_outlets_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusListResponse"];
                };
            };
        };
    };
    list_api_keys_api_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyListResponse"];
                };
            };
        };
    };
    create_api_key_api_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_api_key_api_api_keys__outlet_code__rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlet_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_api_keys__outlet_code__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlet_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_alias_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
